# DOCS http://codecentric.github.io/spring-boot-admin/1.5.0/#_hystrix_ui_module

server:
  context-path:
  port: ${PORT:7070}

info:
  version: 1.5.0
  description: подсистема "Администрирования и управления"

eureka:
  instance:
      prefer-ip-address: false

management:
  context-path: /admin/mgmt

#management.context-path: /mgmt
#endpoints.health.path: /health

turbine:
  aggregator:
    clusterConfig: ORDER,CUSTOMER,CATALOG
  appConfig: order,customer,catalog
  instanceUrlSuffix: /mgmt/hystrix.stream

spring:
  boot:
    admin:
      turbine:
        clusters: ORDER,CUSTOMER,CATALOG
        enabled: true
      context-path: /admin
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

#      turbine:
#        clusters: default
#        url: http://localhost:8989/turbine.stream
#        client.prefer-ip: true
